.gitmodules
README.md

git modules and readme update

---

tinman/keysub.py

Fix emptystring keysub

---

Pipfile
Pipfile.lock
README.md
tinman/sample.py
tinman/txgen.py

Closes #77 
Please note, you must use install `yajl` (e.g.:`apt-get libyajl-dev` on linux or `brew install yaji` on mac) and also `pip install pipenv && pipenv install`, which is also documented in the README.md.

77 stream json

---

README.md
tinman/txgen.py

 #79 reverts #71

---

tinman/txgen.py

[#82] remove very large wait_blocks

---

tinman/txgen.py

[#84] add waitblocks to clear witness round

---

README.md
tinman/main.py
tinman/warden.py

gatling preflight check #93

---

tinman/gatling.py

retriable errors from transaction source #70

---

gatling.conf.example
tinman/gatling.py

makes a distinction from "default" and "not set" for these arguments #96

---

README.md

example after bootstrap #101

---

amountsub.conf.example
tinman/amountsub.py
tinman/main.py

92 amountsub

---

tinman/amountsub.py

110 nested amounts

---

tinman/txgen.py

avoid going over maximum account creation fee #112

---

txgen.conf.example

reverting dd7f0c0 #116

---

tinman/txgen.py

adjusted total_vests #119

---

README.md
durables.conf.example
tinman/durables.py
tinman/main.py

added fixture-like object that must exist for external testing #121

---

README.md

[#128] fix readme

---

tinman/txgen.py

... which also means we no longer have to give a haircut to the top account balances
Closes #125

moved account initial vesting from fee to its own transfer op

---

tinman/submit.py

103 handle stale actions

---

tinman/txgen.py

bumped predicted_transaction_count #133

---

Dockerfile

install yajl #137

---

tinman/txgen.py

fixed #141

---

durables.conf.example
tinman/durables.py

added price feeds to durables #156

---

tinman/durables.py

fixed durable account fees #158

---

test/prefixsub_test.py
tinman/gatling.py
tinman/submit.py
tinman/txgen.py
txgen.conf.example

creates backfill #155

---

test/keysub_test.py
test/txgen_test.py
test/util_test.py
tinman/submit.py
tinman/txgen.py
tinman/util.py

165 backfill signals

---

tinman/gatling.py

added request timeout message #123

---

test/txgen_test.py
tinman/txgen.py
txgen.conf.example

conf + constants #100

---

tinman/txgen.py

logging config #170

---

tinman/warden.py

removed initminer check #182
